export const cities = [
  'ALBENS',
  'ALBY S/CHERAN',
  'ANNECY',
  'ANNECY LE VX',
  'AIX LES BS',
  'ALLEVES',
  'ARGONAY',
  'CESSENS',
  'CHAMBERY',
  'BALME DE SILLINGY',
  'BALMONT',
  'BLOYE',
  'BOUSSY',
  'CHAINAZ LES FRASSES',
  'CHAPEIRY',
  'CHAVANOD',
  'CRAN GEVRIER',
  'CREMPIGNY',
  'CRUSEILLES',
  'CUSY',
  'DESINGY',
  'DOUSSARD',
  'EPAGNY',
  'EPAGNY METZ-TESSY',
  'FAVERGES',
  'FRANGY',
  'GRAND-BORNAND',
  'GRESY S/AIX',
  'GRUFFY',
  'HAUTEVILLE SUR FIER',
  'HERY',
  'LA BIOLLE',
  'LE REVARD',
  'LESCHERAINES',
  'LORNAY',
  'LOVAGNY',
  'MARCELLAZ',
  'MARIGNY',
  'MASSINGY',
  'MENTHONNEX',
  'MEYTHET',
  'METZ TESSY',
  'MONTAGNY',
  'MOYE',
  'MURES',
  'NONGLARD',
  'PRINGY',
  'QUINTAL',
  'RUMILLY',
  'SALES',
  'SEYSSEL',
  'ST EUSEBE',
  'ST FELIX',
  'ST JORIOZ',
  'SERRIERES',
  'ST SYLVESTRE',
  'THUSY',
  'VAL DE FIER',
  'VALLIERES',
  'ENTRELACS',
]

export const citiesItems = cities.map((city) => ({ label: city, value: city }))
