export const materiels: Record<string, string> = {
  '2': 'Chaussures',
  '3': 'Surf',
  '4': 'Vetements',
  '5': 'Fixations',
  '6': 'Batons',
  '7': 'Divers',
  '8': 'Raquettes',
  '9': 'Skis',
  '10': 'Casque',
  '11': 'Snow Blade',
  '12': 'Luge',
  '13': 'Zabsent',
  '14': 'Masque Ski',
  '15': 'Housse Ski',
  '16': 'Boots',
  '17': 'Lunette',
  '18': 'Gants',
  '19': 'Polaire',
  '20': 'Zrefusé',
}
