#!/usr/bin/env bash
#
# Put four double-clickable icons on the Desktop, so the server can be run
# without a terminal.
#
#   ./scripts/install-desktop-icons.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."
REPO="$(pwd)"
# shellcheck source=/dev/null
. "$REPO/scripts/_lib.sh"

DESKTOP="$HOME/Desktop"
[ -d "$DESKTOP" ] || { bad "No Desktop folder found at $DESKTOP"; exit 1; }

# $1 = file name shown on the Desktop, $2 = script, $3 = window title
make_icon() {
  local file="$DESKTOP/$1.command" script="$2" title="$3"
  cat > "$file" <<INNER
#!/bin/bash
# Generated by scripts/install-desktop-icons.sh - safe to delete and regenerate.
printf '\033]0;%s\007' "$title"
cd "$REPO" || { echo "Project folder not found: $REPO"; read -r; exit 1; }
"$REPO/scripts/$script"
STATUS=\$?
echo
if [ \$STATUS -eq 0 ]; then
  echo "Terminé. Vous pouvez fermer cette fenêtre."
else
  echo "Un problème est survenu (voir les lignes rouges ci-dessus)."
fi
echo "Appuyez sur Entrée pour fermer."
read -r
INNER
  chmod +x "$file"
  ok "$1"
}

# The icons are numbered in the order they are used, so adding one renumbers
# the rest. Clear out the previous set first, or the Desktop keeps both the old
# "3 - Arrêter" and the new "4 - Arrêter". Only files this script wrote carry
# the marker line, so nothing else on the Desktop is ever touched.
say "Removing any previous icons"
REMOVED=0
for f in "$DESKTOP"/*.command; do
  [ -f "$f" ] || continue
  if grep -q "Generated by scripts/install-desktop-icons.sh" "$f" 2>/dev/null; then
    rm -f "$f"; REMOVED=$((REMOVED+1))
  fi
done
[ "$REMOVED" -gt 0 ] && ok "Removed $REMOVED old icon(s)" || ok "None to remove"

say "Creating Desktop icons"
make_icon "1 - Démarrer le serveur"     start-server.sh  "Démarrage du serveur"
make_icon "2 - Sauvegardes automatiques" backup-loop.sh  "Sauvegardes automatiques"
make_icon "3 - État du serveur"         status.sh        "État du serveur"
make_icon "4 - Arrêter le serveur"      stop-server.sh   "Arrêt du serveur"

say "Done"
echo "  Four icons are on the Desktop, numbered in the order they are used."
echo "  Double-click one; a Terminal window shows what is happening."
echo
echo "  Icon 2 stays open all day: it saves the database every minute. Leave its"
echo "  window open for the whole sale, and press Ctrl-C in it to stop."
echo
echo "  The first double-click may show \"cannot be opened because it is from an"
echo "  unidentified developer\" - right-click the icon and choose Open instead,"
echo "  once per icon. Files created locally are usually not blocked."
echo
