#!/usr/bin/env bash
#
# Build the USB kit handed to each client PC: the root CA plus a one-click
# installer per platform that adds the hosts entry and trusts the CA.
#
#   ./scripts/make-usb-kit.sh              # uses this Mac's current address
#   ./scripts/make-usb-kit.sh 192.168.1.50 # or a fixed one
#
set -euo pipefail
cd "$(dirname "$0")/.."
# shellcheck source=/dev/null
. "$(dirname "$0")/_lib.sh"

IP="${1:-$(lan_ip || true)}"
[ -n "$IP" ] || { bad "No address given and none detected. Pass it: ./scripts/make-usb-kit.sh 192.168.1.50"; exit 1; }
case "$IP" in
  *.*.*.*) ;;
  *) bad "'$IP' does not look like an IP address"; exit 1 ;;
esac

CAROOT="$(mkcert -CAROOT)"
[ -f "$CAROOT/rootCA.pem" ] || { bad "Root CA not found at $CAROOT"; exit 1; }

KIT="usb-kit"
rm -rf "$KIT"; mkdir -p "$KIT"

say "Building the kit for $IP"

# The CA is public. Its private key must never leave this Mac.
cp "$CAROOT/rootCA.pem" "$KIT/rootCA.pem"
cp "$CAROOT/rootCA.pem" "$KIT/rootCA.crt"     # Windows prefers .crt
if grep -q "PRIVATE KEY" "$KIT"/*.pem "$KIT"/*.crt 2>/dev/null; then
  bad "A private key ended up in the kit - aborting"; rm -rf "$KIT"; exit 1
fi
ok "root CA copied (public certificate only)"

# ---------------------------------------------------------------- Windows
cat > "$KIT/Installer-Windows.bat" <<WIN
@echo off
REM Adds the hosts entry and trusts the local certificate authority.
REM Generated by scripts/make-usb-kit.sh - regenerate if the server IP changes.
setlocal

net session >nul 2>&1
if %errorLevel% neq 0 (
    echo Demande des droits administrateur...
    powershell -Command "Start-Process '%~f0' -Verb RunAs"
    exit /b
)

set HOSTS=%SystemRoot%\System32\drivers\etc\hosts
set ENTRY=$IP  $HOSTNAME_LAN

echo.
echo === Configuration du poste pour la bourse ===
echo.

echo [1/2] Certificat...
certutil -addstore -f "ROOT" "%~dp0rootCA.crt" >nul 2>&1
if %errorLevel% equ 0 (echo     OK - autorite de certification installee) else (echo     ECHEC - certificat non installe)

echo [2/2] Adresse du serveur...
if not exist "%HOSTS%" (echo     ECHEC - fichier hosts introuvable & goto :done)
copy /y "%HOSTS%" "%HOSTS%.backup" >nul 2>&1
REM Drop any previous line for this name, then add the current one.
findstr /v /i /c:"$HOSTNAME_LAN" "%HOSTS%" > "%TEMP%\hosts.new" 2>nul
echo %ENTRY%>> "%TEMP%\hosts.new"
copy /y "%TEMP%\hosts.new" "%HOSTS%" >nul 2>&1
if %errorLevel% equ 0 (echo     OK - %ENTRY%) else (echo     ECHEC - antivirus bloque peut-etre le fichier hosts)
del "%TEMP%\hosts.new" >nul 2>&1

:done
echo.
echo Termine. Ouvrez ensuite : https://$HOSTNAME_LAN
echo.
pause
WIN
ok "Installer-Windows.bat"

# ------------------------------------------------------------------ macOS
cat > "$KIT/Installer-macOS.command" <<MAC
#!/bin/bash
# Adds the hosts entry and trusts the local certificate authority.
# Generated by scripts/make-usb-kit.sh - regenerate if the server IP changes.
set -u
DIR="\$(cd "\$(dirname "\$0")" && pwd)"
ENTRY="$IP  $HOSTNAME_LAN"

echo
echo "=== Configuration du poste pour la bourse ==="
echo
echo "Le mot de passe de cet ordinateur va etre demande."
echo

sudo -v || { echo "Mot de passe refuse. Abandon."; read -r; exit 1; }

echo "[1/2] Certificat..."
if sudo security add-trusted-cert -d -r trustRoot \\
     -k /Library/Keychains/System.keychain "\$DIR/rootCA.pem" 2>/dev/null; then
  echo "    OK - autorite de certification installee"
else
  echo "    Deja installee (ou echec)"
fi

echo "[2/2] Adresse du serveur..."
sudo cp /etc/hosts /etc/hosts.backup 2>/dev/null
# Drop any previous line for this name, then add the current one.
sudo sh -c "grep -v '$HOSTNAME_LAN' /etc/hosts > /tmp/hosts.new && echo '\$ENTRY' >> /tmp/hosts.new && cp /tmp/hosts.new /etc/hosts && rm -f /tmp/hosts.new"
if grep -q "$IP" /etc/hosts 2>/dev/null; then
  echo "    OK - \$ENTRY"
else
  echo "    ECHEC - la ligne n'a pas ete ajoutee"
fi
sudo dscacheutil -flushcache 2>/dev/null || true

echo
echo "Termine. Ouvrez ensuite : https://$HOSTNAME_LAN"
echo "Appuyez sur Entree pour fermer."
read -r
MAC
chmod +x "$KIT/Installer-macOS.command"
ok "Installer-macOS.command"

# ------------------------------------------------------------------- notes
cat > "$KIT/LISEZ-MOI.txt" <<TXT
Configuration d'un poste pour la bourse aux skis
================================================

Serveur : https://$HOSTNAME_LAN   ($IP)

WINDOWS
  Clic droit sur "Installer-Windows.bat" -> "Executer en tant qu'administrateur".

MAC
  Clic droit sur "Installer-macOS.command" -> "Ouvrir", puis "Ouvrir" a nouveau.
  Le mot de passe de la session sera demande.

Ensuite, ouvrir https://$HOSTNAME_LAN dans le navigateur.
Le cadenas doit etre ferme, sans avertissement.

IMPORTANT
  Lancer ce programme AVANT d'ouvrir le site pour la premiere fois.
  Si un avertissement de securite apparait et que l'on clique sur
  "Continuer quand meme", le navigateur garde une exception et affiche
  "Non securise" en permanence. Fermer completement le navigateur
  (pas seulement la fenetre) corrige cela.

  Ne jamais "effacer les donnees du site" : cela supprime les depots et
  les ventes enregistres sur ce poste et pas encore envoyes au serveur.

MODE HORS LIGNE
  Une fois le site ouvert UNE fois avec le serveur allume, ce poste garde
  une copie de l'application. Si le serveur tombe pendant la vente, le
  poste continue de fonctionner, et recharger la page ou en rouvrir une
  nouvelle marche toujours.

  A FAIRE AVANT L'OUVERTURE DES PORTES : ouvrir https://$HOSTNAME_LAN sur
  CHAQUE poste pendant que le serveur fonctionne, et se connecter. Un poste
  qui n'a jamais reussi a ouvrir le site n'a pas de copie locale et
  n'affichera rien si le serveur est en panne.

  Ne pas se deconnecter pendant l'evenement : sans le serveur, il est
  impossible de se reconnecter.

FIREFOX
  Firefox a son propre magasin de certificats :
  Parametres -> Vie privee et securite -> Certificats -> Afficher les
  certificats -> Autorites -> Importer -> rootCA.pem
  Cocher "Confirmer cette AC pour identifier des sites web".

Si l'adresse du serveur change, ce programme doit etre relance sur chaque
poste (il remplace l'ancienne ligne, il n'en ajoute pas une deuxieme).
TXT
ok "LISEZ-MOI.txt"

say "Done"
echo "  Copy the '$KIT' folder to the USB key."
echo "  Server address baked in: $IP"
echo
warn "If the server's address changes, regenerate the kit and re-run it on each PC."
echo
