/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DymoRouteImport } from './routes/dymo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as HiddenPdfsIndexRouteImport } from './routes/hidden-pdfs/index'
import { Route as DepositsIndexRouteImport } from './routes/deposits/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SalesSalesControlRouteImport } from './routes/sales/sales-control'
import { Route as SalesListingRouteImport } from './routes/sales/listing'
import { Route as SalesAddRouteImport } from './routes/sales/add'
import { Route as HiddenPdfsSummaryReturnDepositsRouteImport } from './routes/hidden-pdfs/summary-return-deposits'
import { Route as HiddenPdfsSummaryDepositsRouteImport } from './routes/hidden-pdfs/summary-deposits'
import { Route as HiddenPdfsDepositCashRegisterControlRouteImport } from './routes/hidden-pdfs/deposit-cash-register-control'
import { Route as DepositsProsRouteImport } from './routes/deposits/pros'
import { Route as DepositsPredepositsRouteImport } from './routes/deposits/predeposits'
import { Route as DepositsListingRouteImport } from './routes/deposits/listing'
import { Route as DepositsCashRegisterControlRouteImport } from './routes/deposits/cash-register-control'
import { Route as DepositsArticlesRouteImport } from './routes/deposits/articles'
import { Route as DepositsAddRouteImport } from './routes/deposits/add'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDepotsRouteImport } from './routes/admin/depots'
import { Route as SalesSaleIdEditRouteImport } from './routes/sales/$saleId.edit'
import { Route as DepositsDepositIdEditRouteImport } from './routes/deposits/$depositId.edit'
import { Route as AdminSalesSaleIdEditRouteImport } from './routes/admin/sales_.$saleId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DymoRoute = DymoRouteImport.update({
  id: '/dymo',
  path: '/dymo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddenPdfsIndexRoute = HiddenPdfsIndexRouteImport.update({
  id: '/hidden-pdfs/',
  path: '/hidden-pdfs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsIndexRoute = DepositsIndexRouteImport.update({
  id: '/deposits/',
  path: '/deposits/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSalesControlRoute = SalesSalesControlRouteImport.update({
  id: '/sales/sales-control',
  path: '/sales/sales-control',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesListingRoute = SalesListingRouteImport.update({
  id: '/sales/listing',
  path: '/sales/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesAddRoute = SalesAddRouteImport.update({
  id: '/sales/add',
  path: '/sales/add',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddenPdfsSummaryReturnDepositsRoute =
  HiddenPdfsSummaryReturnDepositsRouteImport.update({
    id: '/hidden-pdfs/summary-return-deposits',
    path: '/hidden-pdfs/summary-return-deposits',
    getParentRoute: () => rootRouteImport,
  } as any)
const HiddenPdfsSummaryDepositsRoute =
  HiddenPdfsSummaryDepositsRouteImport.update({
    id: '/hidden-pdfs/summary-deposits',
    path: '/hidden-pdfs/summary-deposits',
    getParentRoute: () => rootRouteImport,
  } as any)
const HiddenPdfsDepositCashRegisterControlRoute =
  HiddenPdfsDepositCashRegisterControlRouteImport.update({
    id: '/hidden-pdfs/deposit-cash-register-control',
    path: '/hidden-pdfs/deposit-cash-register-control',
    getParentRoute: () => rootRouteImport,
  } as any)
const DepositsProsRoute = DepositsProsRouteImport.update({
  id: '/deposits/pros',
  path: '/deposits/pros',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsPredepositsRoute = DepositsPredepositsRouteImport.update({
  id: '/deposits/predeposits',
  path: '/deposits/predeposits',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsListingRoute = DepositsListingRouteImport.update({
  id: '/deposits/listing',
  path: '/deposits/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsCashRegisterControlRoute =
  DepositsCashRegisterControlRouteImport.update({
    id: '/deposits/cash-register-control',
    path: '/deposits/cash-register-control',
    getParentRoute: () => rootRouteImport,
  } as any)
const DepositsArticlesRoute = DepositsArticlesRouteImport.update({
  id: '/deposits/articles',
  path: '/deposits/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsAddRoute = DepositsAddRouteImport.update({
  id: '/deposits/add',
  path: '/deposits/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/admin/sales',
  path: '/admin/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepotsRoute = AdminDepotsRouteImport.update({
  id: '/admin/depots',
  path: '/admin/depots',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSaleIdEditRoute = SalesSaleIdEditRouteImport.update({
  id: '/sales/$saleId/edit',
  path: '/sales/$saleId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsDepositIdEditRoute = DepositsDepositIdEditRouteImport.update({
  id: '/deposits/$depositId/edit',
  path: '/deposits/$depositId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesSaleIdEditRoute = AdminSalesSaleIdEditRouteImport.update({
  id: '/admin/sales_/$saleId/edit',
  path: '/admin/sales/$saleId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dymo': typeof DymoRoute
  '/login': typeof LoginRoute
  '/admin/depots': typeof AdminDepotsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/deposits/add': typeof DepositsAddRoute
  '/deposits/articles': typeof DepositsArticlesRoute
  '/deposits/cash-register-control': typeof DepositsCashRegisterControlRoute
  '/deposits/listing': typeof DepositsListingRoute
  '/deposits/predeposits': typeof DepositsPredepositsRoute
  '/deposits/pros': typeof DepositsProsRoute
  '/hidden-pdfs/deposit-cash-register-control': typeof HiddenPdfsDepositCashRegisterControlRoute
  '/hidden-pdfs/summary-deposits': typeof HiddenPdfsSummaryDepositsRoute
  '/hidden-pdfs/summary-return-deposits': typeof HiddenPdfsSummaryReturnDepositsRoute
  '/sales/add': typeof SalesAddRoute
  '/sales/listing': typeof SalesListingRoute
  '/sales/sales-control': typeof SalesSalesControlRoute
  '/admin': typeof AdminIndexRoute
  '/deposits': typeof DepositsIndexRoute
  '/hidden-pdfs': typeof HiddenPdfsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/deposits/$depositId/edit': typeof DepositsDepositIdEditRoute
  '/sales/$saleId/edit': typeof SalesSaleIdEditRoute
  '/admin/sales/$saleId/edit': typeof AdminSalesSaleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dymo': typeof DymoRoute
  '/login': typeof LoginRoute
  '/admin/depots': typeof AdminDepotsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/deposits/add': typeof DepositsAddRoute
  '/deposits/articles': typeof DepositsArticlesRoute
  '/deposits/cash-register-control': typeof DepositsCashRegisterControlRoute
  '/deposits/listing': typeof DepositsListingRoute
  '/deposits/predeposits': typeof DepositsPredepositsRoute
  '/deposits/pros': typeof DepositsProsRoute
  '/hidden-pdfs/deposit-cash-register-control': typeof HiddenPdfsDepositCashRegisterControlRoute
  '/hidden-pdfs/summary-deposits': typeof HiddenPdfsSummaryDepositsRoute
  '/hidden-pdfs/summary-return-deposits': typeof HiddenPdfsSummaryReturnDepositsRoute
  '/sales/add': typeof SalesAddRoute
  '/sales/listing': typeof SalesListingRoute
  '/sales/sales-control': typeof SalesSalesControlRoute
  '/admin': typeof AdminIndexRoute
  '/deposits': typeof DepositsIndexRoute
  '/hidden-pdfs': typeof HiddenPdfsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/deposits/$depositId/edit': typeof DepositsDepositIdEditRoute
  '/sales/$saleId/edit': typeof SalesSaleIdEditRoute
  '/admin/sales/$saleId/edit': typeof AdminSalesSaleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dymo': typeof DymoRoute
  '/login': typeof LoginRoute
  '/admin/depots': typeof AdminDepotsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/deposits/add': typeof DepositsAddRoute
  '/deposits/articles': typeof DepositsArticlesRoute
  '/deposits/cash-register-control': typeof DepositsCashRegisterControlRoute
  '/deposits/listing': typeof DepositsListingRoute
  '/deposits/predeposits': typeof DepositsPredepositsRoute
  '/deposits/pros': typeof DepositsProsRoute
  '/hidden-pdfs/deposit-cash-register-control': typeof HiddenPdfsDepositCashRegisterControlRoute
  '/hidden-pdfs/summary-deposits': typeof HiddenPdfsSummaryDepositsRoute
  '/hidden-pdfs/summary-return-deposits': typeof HiddenPdfsSummaryReturnDepositsRoute
  '/sales/add': typeof SalesAddRoute
  '/sales/listing': typeof SalesListingRoute
  '/sales/sales-control': typeof SalesSalesControlRoute
  '/admin/': typeof AdminIndexRoute
  '/deposits/': typeof DepositsIndexRoute
  '/hidden-pdfs/': typeof HiddenPdfsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/deposits/$depositId/edit': typeof DepositsDepositIdEditRoute
  '/sales/$saleId/edit': typeof SalesSaleIdEditRoute
  '/admin/sales_/$saleId/edit': typeof AdminSalesSaleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dymo'
    | '/login'
    | '/admin/depots'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/users'
    | '/deposits/add'
    | '/deposits/articles'
    | '/deposits/cash-register-control'
    | '/deposits/listing'
    | '/deposits/predeposits'
    | '/deposits/pros'
    | '/hidden-pdfs/deposit-cash-register-control'
    | '/hidden-pdfs/summary-deposits'
    | '/hidden-pdfs/summary-return-deposits'
    | '/sales/add'
    | '/sales/listing'
    | '/sales/sales-control'
    | '/admin'
    | '/deposits'
    | '/hidden-pdfs'
    | '/sales'
    | '/deposits/$depositId/edit'
    | '/sales/$saleId/edit'
    | '/admin/sales/$saleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dymo'
    | '/login'
    | '/admin/depots'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/users'
    | '/deposits/add'
    | '/deposits/articles'
    | '/deposits/cash-register-control'
    | '/deposits/listing'
    | '/deposits/predeposits'
    | '/deposits/pros'
    | '/hidden-pdfs/deposit-cash-register-control'
    | '/hidden-pdfs/summary-deposits'
    | '/hidden-pdfs/summary-return-deposits'
    | '/sales/add'
    | '/sales/listing'
    | '/sales/sales-control'
    | '/admin'
    | '/deposits'
    | '/hidden-pdfs'
    | '/sales'
    | '/deposits/$depositId/edit'
    | '/sales/$saleId/edit'
    | '/admin/sales/$saleId/edit'
  id:
    | '__root__'
    | '/'
    | '/dymo'
    | '/login'
    | '/admin/depots'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/users'
    | '/deposits/add'
    | '/deposits/articles'
    | '/deposits/cash-register-control'
    | '/deposits/listing'
    | '/deposits/predeposits'
    | '/deposits/pros'
    | '/hidden-pdfs/deposit-cash-register-control'
    | '/hidden-pdfs/summary-deposits'
    | '/hidden-pdfs/summary-return-deposits'
    | '/sales/add'
    | '/sales/listing'
    | '/sales/sales-control'
    | '/admin/'
    | '/deposits/'
    | '/hidden-pdfs/'
    | '/sales/'
    | '/deposits/$depositId/edit'
    | '/sales/$saleId/edit'
    | '/admin/sales_/$saleId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DymoRoute: typeof DymoRoute
  LoginRoute: typeof LoginRoute
  AdminDepotsRoute: typeof AdminDepotsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DepositsAddRoute: typeof DepositsAddRoute
  DepositsArticlesRoute: typeof DepositsArticlesRoute
  DepositsCashRegisterControlRoute: typeof DepositsCashRegisterControlRoute
  DepositsListingRoute: typeof DepositsListingRoute
  DepositsPredepositsRoute: typeof DepositsPredepositsRoute
  DepositsProsRoute: typeof DepositsProsRoute
  HiddenPdfsDepositCashRegisterControlRoute: typeof HiddenPdfsDepositCashRegisterControlRoute
  HiddenPdfsSummaryDepositsRoute: typeof HiddenPdfsSummaryDepositsRoute
  HiddenPdfsSummaryReturnDepositsRoute: typeof HiddenPdfsSummaryReturnDepositsRoute
  SalesAddRoute: typeof SalesAddRoute
  SalesListingRoute: typeof SalesListingRoute
  SalesSalesControlRoute: typeof SalesSalesControlRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DepositsIndexRoute: typeof DepositsIndexRoute
  HiddenPdfsIndexRoute: typeof HiddenPdfsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  DepositsDepositIdEditRoute: typeof DepositsDepositIdEditRoute
  SalesSaleIdEditRoute: typeof SalesSaleIdEditRoute
  AdminSalesSaleIdEditRoute: typeof AdminSalesSaleIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dymo': {
      id: '/dymo'
      path: '/dymo'
      fullPath: '/dymo'
      preLoaderRoute: typeof DymoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden-pdfs/': {
      id: '/hidden-pdfs/'
      path: '/hidden-pdfs'
      fullPath: '/hidden-pdfs'
      preLoaderRoute: typeof HiddenPdfsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/': {
      id: '/deposits/'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof DepositsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/sales-control': {
      id: '/sales/sales-control'
      path: '/sales/sales-control'
      fullPath: '/sales/sales-control'
      preLoaderRoute: typeof SalesSalesControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/listing': {
      id: '/sales/listing'
      path: '/sales/listing'
      fullPath: '/sales/listing'
      preLoaderRoute: typeof SalesListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/add': {
      id: '/sales/add'
      path: '/sales/add'
      fullPath: '/sales/add'
      preLoaderRoute: typeof SalesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden-pdfs/summary-return-deposits': {
      id: '/hidden-pdfs/summary-return-deposits'
      path: '/hidden-pdfs/summary-return-deposits'
      fullPath: '/hidden-pdfs/summary-return-deposits'
      preLoaderRoute: typeof HiddenPdfsSummaryReturnDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden-pdfs/summary-deposits': {
      id: '/hidden-pdfs/summary-deposits'
      path: '/hidden-pdfs/summary-deposits'
      fullPath: '/hidden-pdfs/summary-deposits'
      preLoaderRoute: typeof HiddenPdfsSummaryDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden-pdfs/deposit-cash-register-control': {
      id: '/hidden-pdfs/deposit-cash-register-control'
      path: '/hidden-pdfs/deposit-cash-register-control'
      fullPath: '/hidden-pdfs/deposit-cash-register-control'
      preLoaderRoute: typeof HiddenPdfsDepositCashRegisterControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/pros': {
      id: '/deposits/pros'
      path: '/deposits/pros'
      fullPath: '/deposits/pros'
      preLoaderRoute: typeof DepositsProsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/predeposits': {
      id: '/deposits/predeposits'
      path: '/deposits/predeposits'
      fullPath: '/deposits/predeposits'
      preLoaderRoute: typeof DepositsPredepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/listing': {
      id: '/deposits/listing'
      path: '/deposits/listing'
      fullPath: '/deposits/listing'
      preLoaderRoute: typeof DepositsListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/cash-register-control': {
      id: '/deposits/cash-register-control'
      path: '/deposits/cash-register-control'
      fullPath: '/deposits/cash-register-control'
      preLoaderRoute: typeof DepositsCashRegisterControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/articles': {
      id: '/deposits/articles'
      path: '/deposits/articles'
      fullPath: '/deposits/articles'
      preLoaderRoute: typeof DepositsArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/add': {
      id: '/deposits/add'
      path: '/deposits/add'
      fullPath: '/deposits/add'
      preLoaderRoute: typeof DepositsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/depots': {
      id: '/admin/depots'
      path: '/admin/depots'
      fullPath: '/admin/depots'
      preLoaderRoute: typeof AdminDepotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$saleId/edit': {
      id: '/sales/$saleId/edit'
      path: '/sales/$saleId/edit'
      fullPath: '/sales/$saleId/edit'
      preLoaderRoute: typeof SalesSaleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/$depositId/edit': {
      id: '/deposits/$depositId/edit'
      path: '/deposits/$depositId/edit'
      fullPath: '/deposits/$depositId/edit'
      preLoaderRoute: typeof DepositsDepositIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales_/$saleId/edit': {
      id: '/admin/sales_/$saleId/edit'
      path: '/admin/sales/$saleId/edit'
      fullPath: '/admin/sales/$saleId/edit'
      preLoaderRoute: typeof AdminSalesSaleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DymoRoute: DymoRoute,
  LoginRoute: LoginRoute,
  AdminDepotsRoute: AdminDepotsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DepositsAddRoute: DepositsAddRoute,
  DepositsArticlesRoute: DepositsArticlesRoute,
  DepositsCashRegisterControlRoute: DepositsCashRegisterControlRoute,
  DepositsListingRoute: DepositsListingRoute,
  DepositsPredepositsRoute: DepositsPredepositsRoute,
  DepositsProsRoute: DepositsProsRoute,
  HiddenPdfsDepositCashRegisterControlRoute:
    HiddenPdfsDepositCashRegisterControlRoute,
  HiddenPdfsSummaryDepositsRoute: HiddenPdfsSummaryDepositsRoute,
  HiddenPdfsSummaryReturnDepositsRoute: HiddenPdfsSummaryReturnDepositsRoute,
  SalesAddRoute: SalesAddRoute,
  SalesListingRoute: SalesListingRoute,
  SalesSalesControlRoute: SalesSalesControlRoute,
  AdminIndexRoute: AdminIndexRoute,
  DepositsIndexRoute: DepositsIndexRoute,
  HiddenPdfsIndexRoute: HiddenPdfsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  DepositsDepositIdEditRoute: DepositsDepositIdEditRoute,
  SalesSaleIdEditRoute: SalesSaleIdEditRoute,
  AdminSalesSaleIdEditRoute: AdminSalesSaleIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
