/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DymoRouteImport } from './routes/dymo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepotVenteIndexRouteImport } from './routes/depot-vente/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DepotVenteDepotRouteImport } from './routes/depot-vente/depot'
import { Route as AdminVentesRouteImport } from './routes/admin/ventes'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDepotsRouteImport } from './routes/admin/depots'

const DymoRoute = DymoRouteImport.update({
  id: '/dymo',
  path: '/dymo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepotVenteIndexRoute = DepotVenteIndexRouteImport.update({
  id: '/depot-vente/',
  path: '/depot-vente/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepotVenteDepotRoute = DepotVenteDepotRouteImport.update({
  id: '/depot-vente/depot',
  path: '/depot-vente/depot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVentesRoute = AdminVentesRouteImport.update({
  id: '/admin/ventes',
  path: '/admin/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepotsRoute = AdminDepotsRouteImport.update({
  id: '/admin/depots',
  path: '/admin/depots',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dymo': typeof DymoRoute
  '/admin/depots': typeof AdminDepotsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/ventes': typeof AdminVentesRoute
  '/depot-vente/depot': typeof DepotVenteDepotRoute
  '/admin': typeof AdminIndexRoute
  '/depot-vente': typeof DepotVenteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dymo': typeof DymoRoute
  '/admin/depots': typeof AdminDepotsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/ventes': typeof AdminVentesRoute
  '/depot-vente/depot': typeof DepotVenteDepotRoute
  '/admin': typeof AdminIndexRoute
  '/depot-vente': typeof DepotVenteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dymo': typeof DymoRoute
  '/admin/depots': typeof AdminDepotsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/ventes': typeof AdminVentesRoute
  '/depot-vente/depot': typeof DepotVenteDepotRoute
  '/admin/': typeof AdminIndexRoute
  '/depot-vente/': typeof DepotVenteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dymo'
    | '/admin/depots'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/ventes'
    | '/depot-vente/depot'
    | '/admin'
    | '/depot-vente'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dymo'
    | '/admin/depots'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/ventes'
    | '/depot-vente/depot'
    | '/admin'
    | '/depot-vente'
  id:
    | '__root__'
    | '/'
    | '/dymo'
    | '/admin/depots'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/ventes'
    | '/depot-vente/depot'
    | '/admin/'
    | '/depot-vente/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DymoRoute: typeof DymoRoute
  AdminDepotsRoute: typeof AdminDepotsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVentesRoute: typeof AdminVentesRoute
  DepotVenteDepotRoute: typeof DepotVenteDepotRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DepotVenteIndexRoute: typeof DepotVenteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dymo': {
      id: '/dymo'
      path: '/dymo'
      fullPath: '/dymo'
      preLoaderRoute: typeof DymoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depot-vente/': {
      id: '/depot-vente/'
      path: '/depot-vente'
      fullPath: '/depot-vente'
      preLoaderRoute: typeof DepotVenteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depot-vente/depot': {
      id: '/depot-vente/depot'
      path: '/depot-vente/depot'
      fullPath: '/depot-vente/depot'
      preLoaderRoute: typeof DepotVenteDepotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ventes': {
      id: '/admin/ventes'
      path: '/admin/ventes'
      fullPath: '/admin/ventes'
      preLoaderRoute: typeof AdminVentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/depots': {
      id: '/admin/depots'
      path: '/admin/depots'
      fullPath: '/admin/depots'
      preLoaderRoute: typeof AdminDepotsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DymoRoute: DymoRoute,
  AdminDepotsRoute: AdminDepotsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVentesRoute: AdminVentesRoute,
  DepotVenteDepotRoute: DepotVenteDepotRoute,
  AdminIndexRoute: AdminIndexRoute,
  DepotVenteIndexRoute: DepotVenteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
